//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XivRes.FontGenerator.rc
//
#define IDD_FACEELEMENTEDITOR           101
#define IDC_COMBO_FONT_RENDERER         1001
#define IDC_COMBO_FONT                  1002
#define IDC_COMBO_DIRECTWRITE_RENDERMODE 1004
#define IDC_COMBO_FONT_WEIGHT           1005
#define IDC_COMBO_FONT_STYLE            1006
#define IDC_COMBO_FONT_STRETCH          1007
#define IDC_COMBO_DIRECTWRITE_MEASUREMODE 1008
#define IDC_EDIT_FONT_PATH              1009
#define IDC_EDIT_FONT_FACEINDEX         1010
#define IDC_BUTTON_LOCATEFILE           1011
#define IDC_CHECK_FREETYPE_NOSCALE      1012
#define IDC_COMBO_DIRECTWRITE_GRIDFITMODE 1013
#define IDC_LIST_CODEPOINTS             1014
#define IDC_EDIT_ADJUSTMENT_BASELINESHIFT 1015
#define IDC_EDIT_ADJUSTMENT_LETTERSPACING 1016
#define IDC_EDIT_ADJUSTMENT_GAMMA       1017
#define IDC_EDIT_EMPTY_ASCENT           1018
#define IDC_EDIT_EMPTY_LINEHEIGHT       1019
#define IDC_CHECK_FREETYPE_NOHINTING    1020
#define IDC_CHECK_FREETYPE_NOBITMAP     1021
#define IDC_CHECK_FREETYPE_FORCEAUTOHINT 1022
#define IDC_CHECK_FREETYPE_NOAUTOHINT   1023
#define IDC_EDIT_UNICODEBLOCKS_SEARCH   1024
#define IDC_LIST_UNICODEBLOCKS_SEARCHRESULTS 1025
#define IDC_EDIT_ADDCUSTOMRANGE_INPUT   1026
#define IDC_BUTTON_ADDCUSTOMRANGE_ADD   1027
#define IDC_BUTTON_CODEPOINTS_DELETE    1028
#define IDC_CHECK_CODEPOINTS_OVERWRITE  1029
#define IDC_BUTTON_UNICODEBLOCKS_ADD    1030
#define IDC_COMBO_FONT_SIZE             1031
#define IDC_EDIT_ADJUSTMENT_LETTERSPACING2 1032
#define IDC_EDIT_ADJUSTMENT_HORIZONTALOFFSET 1032

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
