//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XivAlexander_ja.rc
//
#define IDR_TRAY_MENU                   105
#define IDR_CONFIG_EDITOR_MENU          106
#define IDR_LOG_MENU                    107
#define IDS_ERROR_LOADER_NOT_FOUND      109
#define IDS_ERROR_CONFIGURATION_LOAD    110
#define IDS_LOG_NEW_CONFIG              111
#define IDS_ERROR_CONFIGURATION_SAVE    112
#define IDS_ERROR_CONFIGURATION_PARSE_VALUE 113
#define IDS_ERROR_GAME_WINDOW_NOT_FOUND 114
#define IDS_ERROR_UNLOAD_XIVALEXANDER   115
#define IDS_LOG_XIVALEXANDER_INITIALIZED 116
#define IDS_ERROR_FREEGAMEMUTEX         117
#define IDS_ERROR_UNEXPECTED            118
#define IDS_ERROR_UNLOAD_SOCKET         119
#define IDS_ERROR_UNLOAD_WNDPROC        120
#define IDS_ERROR_INJECT                121
#define IDS_WARNING_ZEROPING            122
#define IDS_ERROR_FREEGAMEMUTEX_CLOSEHANDLE 123
#define IDS_PINGTRACKER_START           124
#define IDS_PINGTRACKER_END             125
#define IDS_PINGTRACKER_END_FAILURE_COUNT 126
#define IDS_PINGTRACKER_END_ERROR       127
#define IDS_SOCKETHOOK_SOCKET_FOUND     128
#define IDS_SOCKETHOOK_SOCKET_IGNORED_NOT_IPV4 129
#define IDS_SOCKETHOOK_SOCKET_IGNORED_IP 130
#define IDS_SOCKETHOOK_SOCKET_IGNORED_PORT 131
#define IDS_SOCKETHOOK_SOCKET_DETACH    132
#define IDS_SOCKETHOOK_SOCKET_DESCRIBE_TITLE 133
#define IDS_SOCKETHOOK_SOCKET_DESCRIBE_SOCKET_LATENCY 134
#define IDS_SOCKETHOOK_SOCKET_DESCRIBE_SOCKET_LATENCY_FAILURE 135
#define IDS_SOCKETHOOK_SOCKET_DESCRIBE_PING_LATENCY 136
#define IDS_SOCKETHOOK_SOCKET_DESCRIBE_PING_LATENCY_FAILURE 137
#define IDS_SOCKETHOOK_SOCKET_DESCRIBE_RESPONSE_DELAY 138
#define IDS_CONFIRM_CONFIG_WINDOW_CLOSE 139
#define IDS_LOG_SAVED                   140
#define IDS_ERROR_LOG_SAVE              141
#define IDS_WARNING_GAME_PARAMETER_PARSE 142
#define IDS_CONFIRM_MAIN_WINDOW_CLOSE   143
#define IDS_CONFIRM_EXIT_GAME           144
#define IDS_ERROR_UPDATE_CHECK_LAUNCH   145
#define IDS_CONFIRM_RESTART_GAME        146
#define IDS_FAQ                         147
#define IDS_APP_NAME                    148
#define IDS_WINDOW_RUNTIME_CONFIG_EDITOR 149
#define IDS_WINDOW_OPCODE_CONFIG_EDITOR 150
#define IDS_WINDOW_LOG                  151
#define IDS_LOG_NEW_CONFIG2             152
#define ID_40001                        40001
#define ID_TRAYMENU_CONFIGURATION_LANGUAGE_JAPANESE 40002
#define ID_TRAYMENU_USEIPCTYPEFINDER    40003
#define ID_TRAYMENU_UNLOADXIVALEXANDER  40006
#define ID_FILE_REVERT                  40012
#define ID_FILE_SAVE                    40013
#define ID_VIEW_ALWAYSONTOP             40014
#define ID_FILE_CLEAR                   40016
#define ID_TRAYMENU_KEEPGAMEWINDOWALWAYSONTOP 40028
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_ENABLE 40029
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USEDELAYDETECTION 40031
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USELOGGING 40032
#define ID_TRAYMENU_USEALLIPCMESSAGELOGGER 40034
#define ID_TRAYMENU_CURRENTINFO         40035
#define ID_TRAYMENU_USEEFFECTAPPLICATIONDELAYLOGGER 40036
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USELATENCYCORRECTION 40037
#define ID_TRAYMENU_NETWORKING_REDUCEPACKETDELAY 40052
#define ID_TRAYMENU_NETWORKING_TAKEOVERLOOPBACKADDRESSES 40053
#define ID_TRAYMENU_NETWORKING_TAKEOVERALLADDRESSES 40055
#define ID_TRAYMENU_NETWORKING_RELEASEALLCONNECTIONS 40058
#define ID_TRAYMENU_NETWORKING_TAKEOVERPRIVATEADDRESSES 40059
#define ID_TRAYMENU_NETWORKING_TAKEOVERALLPORTS 40061
#define ID_TRAYMENU_CHECKFORUPDATES     40063
#define ID_TRAYMENU_EXITGAME            40065
#define ID_TRAYMENU_RESTARTGAME_RESTART 40073
#define ID_TRAYMENU_RESTARTGAME_USEDIRECTX11 40074
#define ID_TRAYMENU_RESTARTGAME_USEXIVALEXANDER 40075
#define ID_TRAYMENU_RESTARTGAME_USEPARAMETEROBFUSCATION 40076
#define ID_TRAYMENU_RESTARTGAME_USEELEVATION 40078
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USEEARLYPENALTY 40081
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_PREVIEWMODE 40082
#define ID_TRAYMENU_CONFIGURATION_SHOWLOGGINGWINDOW 40087
#define ID_TRAYMENU_CONFIGURATION_SHOWCONTROLWINDOW 40088
#define ID_TRAYMENU_CONFIGURATION_EDITRUNTIMECONFIGURATION 40089
#define ID_TRAYMENU_CONFIGURATION_EDITOPCODECONFIGURATION 40090
#define ID_TRAYMENU_CONFIGURATION_LANGUAGE_ENGLISH 40091
#define ID_TRAYMENU_CONFIGURATION_LANGUAGE_KOREAN 40092
#define ID_TRAYMENU_CONFIGURATION_RELOAD 40093
#define ID_TRAYMENU_CONFIGURATION_LANGUAGE_SYSTEMDEFAULT 40095
#define ID_FILE_CLOSE                   40099

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
