//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XivAlexander.rc
//
#define IDI_TRAY_ICON                   104
#define IDR_TRAY_MENU                   105
#define IDR_CONFIG_EDITOR_MENU          106
#define IDR_LOG_MENU                    107
#define ID_TRAYMENU_USEIPCTYPEFINDER    40003
#define ID_TRAYMENU_SHOWLOGGINGWINDOW   40004
#define ID_TRAYMENU_RELOADCONFIGURATION 40005
#define ID_TRAYMENU_UNLOADXIVALEXANDER  40006
#define ID_TRAYMENU_CURRENT_INFO        40009
#define ID_TRAYMENU_EDITCONFIGURATION   40010
#define ID_FILE_APPLY                   40011
#define ID_FILE_REVERT                  40012
#define ID_FILE_SAVE                    40013
#define ID_VIEW_ALWAYSONTOP             40014
#define ID_FILE_CLEAR                   40016
#define ID_TRAYMENU_SHOWCONTROLWINDOW   40019
#define ID_FEATURES_USEHIGHLATENCYMITIGATION 40025
#define ID_FEATURES_USEDELAYDETECTION   40026
#define ID_FEATURES_USELOGGING          40027
#define ID_TRAYMENU_KEEPGAMEWINDOWALWAYSONTOP 40028
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_ENABLE 40029
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USEDELAYDETECTION 40031
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USELOGGING 40032
#define ID_TRAYMENU_USEALLIPCMESSAGELOGGER 40034
#define ID_TRAYMENU_CURRENTINFO         40035
#define ID_TRAYMENU_USEEFFECTAPPLICATIONDELAYLOGGER 40036
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USELATENCYCORRECTION 40037
#define ID_TRAYMENU_REDUCEPACKETDELAY   40038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40045
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
