//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XivAlexander.rc
//
#define IDI_TRAY_ICON                   104
#define IDR_TRAY_MENU                   105
#define IDR_CONFIG_EDITOR_MENU          106
#define IDR_LOG_MENU                    107
#define IDR_RT_MANIFEST1                108
#define IDR_RT_MANIFEST_LATE_ACTIVATION 108
#define ID_TRAYMENU_USEIPCTYPEFINDER    40003
#define ID_TRAYMENU_SHOWLOGGINGWINDOW   40004
#define ID_TRAYMENU_RELOADCONFIGURATION 40005
#define ID_TRAYMENU_UNLOADXIVALEXANDER  40006
#define ID_TRAYMENU_CURRENT_INFO        40009
#define ID_TRAYMENU_EDITCONFIGURATION   40010
#define ID_FILE_APPLY                   40011
#define ID_FILE_REVERT                  40012
#define ID_FILE_SAVE                    40013
#define ID_VIEW_ALWAYSONTOP             40014
#define ID_FILE_CLEAR                   40016
#define ID_TRAYMENU_SHOWCONTROLWINDOW   40019
#define ID_FEATURES_USEHIGHLATENCYMITIGATION 40025
#define ID_FEATURES_USEDELAYDETECTION   40026
#define ID_FEATURES_USELOGGING          40027
#define ID_TRAYMENU_KEEPGAMEWINDOWALWAYSONTOP 40028
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_ENABLE 40029
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USEDELAYDETECTION 40031
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USELOGGING 40032
#define ID_TRAYMENU_USEALLIPCMESSAGELOGGER 40034
#define ID_TRAYMENU_CURRENTINFO         40035
#define ID_TRAYMENU_USEEFFECTAPPLICATIONDELAYLOGGER 40036
#define ID_TRAYMENU_HIGHLATENCYMITIGATION_USELATENCYCORRECTION 40037
#define ID_TRAYMENU_REDUCEPACKETDELAY   40038
#define ID_TRAYMENU_EDITRUNTIMECONFIGURATION 40045
#define ID_MENU_EDITOPCODECONFIGURATION 40046
#define ID_TRAYMENU_EDITOPCODECONFIGURATION 40047
#define ID_Menu                         40048
#define ID_NETWORKING_TAKEOVERLOOPBACKADDRESSES 40049
#define ID_NETWORKING_TAKEOVERLOCALADDRESSES 40050
#define ID_NETWORKING_TAKEOVERALLADDRESSES 40051
#define ID_TRAYMENU_NETWORKING_REDUCEPACKETDELAY 40052
#define ID_TRAYMENU_NETWORKING_TAKEOVERLOOPBACKADDRESSES 40053
#define ID_TRAYMENU_NETWORKING_TAKEOVERLOCALADDRESSES 40054
#define ID_TRAYMENU_NETWORKING_TAKEOVERALLADDRESSES 40055
#define ID_NETWORKING_RELEASEALLCONNECTIONS 40056
#define ID_Menu40057                    40057
#define ID_TRAYMENU_NETWORKING_RELEASEALLCONNECTIONS 40058
#define ID_TRAYMENU_NETWORKING_TAKEOVERPRIVATEADDRESSES 40059
#define ID_NETWORKING_TAKEOVERALLPORTS  40060
#define ID_TRAYMENU_NETWORKING_TAKEOVERALLPORTS 40061
#define ID_MENU_CHECKFORUPDATES         40062
#define ID_TRAYMENU_CHECKFORUPDATES     40063
#define ID_MENU_QUITGAME                40064
#define ID_TRAYMENU_EXITGAME            40065
#define ID_TRAYMENU_RESTARTGAME         40066
#define ID_TRAYMENU_RESTARTGAMEWITHOUTXIVALEXANDER 40067
#define ID_Menu40068                    40068
#define ID_RESTARTGAME_USEDIRECTX11     40069
#define ID_RESTARTGAME_USEXIVALEXANDER  40070
#define ID_RESTARTGAME_USEDIRECTX12     40071
#define ID_RESTARTGAME_USEPARAMETEROBFUSCATION 40072
#define ID_TRAYMENU_RESTARTGAME_RESTART 40073
#define ID_TRAYMENU_RESTARTGAME_USEDIRECTX11 40074
#define ID_TRAYMENU_RESTARTGAME_USEXIVALEXANDER 40075
#define ID_TRAYMENU_RESTARTGAME_USEPARAMETEROBFUSCATION 40076
#define ID_RESTARTGAME_USEELEVATION     40077
#define ID_TRAYMENU_RESTARTGAME_USEELEVATION 40078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40079
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
